run:
  timeout: 5m
  output:
    format: tab
  skip-dirs:
    - vendor
  go: '1.17'

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
      - diagnostic
    disabled-checks:
      - unnamedResult
    settings:
      hugeParam:
        sizeThreshold: 512
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
      - nilness
      - sigchanyzer
      - stringintconv
      - unusedwrite
  lll:
    line-length: 140
  misspell:
    locale: US
  nlreturn:
    block-size: 5
  revive:
    rules:
      - name: if-return
        disabled: true

linters:
  enable:
    - dupl
    - exportloopref
    - gas
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosimple
    - govet
    - ineffassign
    - ireturn
    - lll
    - maintidx
    - makezero
    - megacheck
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - prealloc
    - revive
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
  fast: false
  disable-all: true

issues:
  exclude-rules:
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "should have a package comment, unless it's in another file for this package"
      linters:
        - golint
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - govet
        - lll
        - nlreturn

service:
  golangci-lint-version: 1.53.x
